apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../platform/namespace-policy

patches:
  - target:
      version: v1
      kind: Namespace
      name: mymusic-coach
    patch: |-
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: baseline
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce-version
        value: latest
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit
        value: restricted
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit-version
        value: latest
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: restricted
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn-version
        value: latest
