"""
Authenticates pretix staff users via a short-lived signed JWT
generated by the platform API. Token is passed as ?sso_token=...
in the URL. Valid for 60 s; expired/tampered tokens fall through
to the normal pretix login form (graceful degradation).
"""
import os

_SECRET = os.environ.get('PRETIX_SSO_SECRET', '')
_PARAM = 'sso_token'


class SSOTokenMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        token = request.GET.get(_PARAM, '')
        if token and _SECRET and not request.user.is_authenticated:
            self._try_login(request, token)
        return self.get_response(request)

    def _try_login(self, request, token):
        try:
            import jwt as pyjwt
            payload = pyjwt.decode(token, _SECRET, algorithms=['HS256'])
            email = (payload.get('email') or '').lower().strip()
            if not email:
                return
            from pretix.base.models import User
            user = User.objects.filter(email=email, is_staff=True, is_active=True).first()
            if user:
                from django.contrib.auth import login
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(request, user)
        except Exception:
            pass  # Expired or invalid token — show normal login form
