'use client';

import { useParams } from 'next/navigation';
import Link from 'next/link';
import { gql, useMutation, useQuery } from '@apollo/client';
import { useEffect, useState } from 'react';
import RoleGate from '@/components/auth/RoleGate';
import { BookOpen, Plus, Save, Trash2 } from 'lucide-react';

const GET=gql`query CourseBuilder($id:ID!){course(id:$id){id slug title description shortSummary level price currency isFreeTier language instruments musicStyles thumbnailUrl status sections{id title order lessons{id title description videoUrl durationMin isFreePreview order xpReward}}}}`;
const UPDATE=gql`mutation UpdateCourseBuilder($id:ID!,$input:UpdateCourseInput!){updateCourse(id:$id,input:$input){id title description shortSummary level price currency thumbnailUrl status}}`;
const ADD_SECTION=gql`mutation AddSection($input:CreateSectionInput!){createSection(input:$input){id}}`;
const DELETE_SECTION=gql`mutation DeleteSection($id:ID!){deleteSection(id:$id)}`;
const ADD_LESSON=gql`mutation AddLesson($input:CreateLessonInput!){createLesson(input:$input){id}}`;
const UPDATE_LESSON=gql`mutation UpdateLesson($id:ID!,$input:UpdateLessonInput!){updateLesson(id:$id,input:$input){id}}`;
const DELETE_LESSON=gql`mutation DeleteLesson($id:ID!){deleteLesson(id:$id)}`;
const PUBLISH=gql`mutation PublishBuilderCourse($id:ID!){publishCourse(id:$id){id status}}`;

export default function CourseBuilderPage(){
 const {courseId}=useParams<{courseId:string}>();const {data,loading,error,refetch}=useQuery(GET,{variables:{id:courseId}});
 const [update,{loading:saving}]=useMutation(UPDATE);const [addSection]=useMutation(ADD_SECTION);const [deleteSection]=useMutation(DELETE_SECTION);
 const [addLesson]=useMutation(ADD_LESSON);const [updateLesson]=useMutation(UPDATE_LESSON);const [deleteLesson]=useMutation(DELETE_LESSON);const [publish]=useMutation(PUBLISH);
 const [form,setForm]=useState({title:'',description:'',shortSummary:'',level:'BEGINNER',price:'0',currency:'CHF',language:'en',instruments:'',musicStyles:'',thumbnailUrl:''});
 const [sectionTitle,setSectionTitle]=useState('');const [lessonDraft,setLessonDraft]=useState<Record<string,any>>({});const [editing,setEditing]=useState<any>(null);
 useEffect(()=>{const course=data?.course;if(course)setForm({title:course.title,description:course.description??'',shortSummary:course.shortSummary??'',level:course.level,price:String(course.price),currency:course.currency,language:course.language,instruments:(course.instruments??[]).join(', '),musicStyles:(course.musicStyles??[]).join(', '),thumbnailUrl:course.thumbnailUrl??''});},[data]);
 const course=data?.course;
 async function saveCourse(e:React.FormEvent){e.preventDefault();await update({variables:{id:courseId,input:{title:form.title.trim(),description:form.description.trim()||null,shortSummary:form.shortSummary.trim()||null,level:form.level,price:Number(form.price),currency:form.currency,language:form.language,instruments:form.instruments.split(',').map(v=>v.trim()).filter(Boolean),musicStyles:form.musicStyles.split(',').map(v=>v.trim()).filter(Boolean),thumbnailUrl:form.thumbnailUrl.trim()||null,isFreeTier:Number(form.price)===0}}});await refetch();}
 async function createSection(e:React.FormEvent){e.preventDefault();if(!sectionTitle.trim())return;await addSection({variables:{input:{courseId,title:sectionTitle.trim(),order:course.sections?.length??0}}});setSectionTitle('');await refetch();}
 async function createLesson(sectionId:string){const draft=lessonDraft[sectionId]??{};if(!draft.title?.trim())return;await addLesson({variables:{input:{sectionId,title:draft.title.trim(),description:draft.description?.trim()||null,videoUrl:draft.videoUrl?.trim()||null,durationMin:Number(draft.durationMin||0),isFreePreview:Boolean(draft.isFreePreview),order:course.sections.find((s:any)=>s.id===sectionId)?.lessons?.length??0,xpReward:10}}});setLessonDraft({...lessonDraft,[sectionId]:{}});await refetch();}
 async function saveLesson(){await updateLesson({variables:{id:editing.id,input:{title:editing.title.trim(),description:editing.description?.trim()||null,videoUrl:editing.videoUrl?.trim()||null,durationMin:Number(editing.durationMin||0),isFreePreview:Boolean(editing.isFreePreview)}}});setEditing(null);await refetch();}
 return <RoleGate allow={['TEACHER','ADMIN']} callbackUrl={`/dashboard/teacher/courses/${courseId}`}><main className="mx-auto max-w-6xl px-6 py-10">
  <Link href="/dashboard/teacher/content" className="text-sm text-primary-700">← Pillar studio</Link>{loading?<p className="mt-8">Loading…</p>:error||!course?<p className="mt-8 text-red-600">{error?.message??'Course not found.'}</p>:<>
  <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-serif text-3xl font-bold">Course builder</h1><p className="text-sm text-gray-600">{course.status} · /courses/{course.slug}</p></div>{course.status==='DRAFT'&&<button className="btn-primary rounded-lg px-4 py-2" onClick={async()=>{await publish({variables:{id:courseId}});await refetch();}}>Publish course</button>}</div>
  <form onSubmit={saveCourse} className="card mt-8 space-y-4 p-6"><h2 className="text-xl font-semibold">Course information</h2>
   <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Title<input className="input mt-1 w-full" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="text-sm font-medium">Short summary<input className="input mt-1 w-full" value={form.shortSummary} onChange={e=>setForm({...form,shortSummary:e.target.value})}/></label></div>
   <label className="block text-sm font-medium">Description<textarea rows={5} className="input mt-1 w-full" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
   <div className="grid gap-4 sm:grid-cols-4"><label className="text-sm font-medium">Complexity<select className="input mt-1 w-full" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}>{['BEGINNER','ELEMENTARY','INTERMEDIATE','ADVANCED','PROFESSIONAL'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-sm font-medium">Price<input type="number" min="0" step=".01" className="input mt-1 w-full" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label className="text-sm font-medium">Currency<input className="input mt-1 w-full" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></label><label className="text-sm font-medium">Language<input className="input mt-1 w-full" value={form.language} onChange={e=>setForm({...form,language:e.target.value})}/></label></div>
   <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Instruments<input className="input mt-1 w-full" value={form.instruments} onChange={e=>setForm({...form,instruments:e.target.value})}/></label><label className="text-sm font-medium">Styles<input className="input mt-1 w-full" value={form.musicStyles} onChange={e=>setForm({...form,musicStyles:e.target.value})}/></label></div>
   <label className="block text-sm font-medium">Cover image URL<input type="url" className="input mt-1 w-full" value={form.thumbnailUrl} onChange={e=>setForm({...form,thumbnailUrl:e.target.value})}/></label>
   <button disabled={saving} className="btn-primary inline-flex items-center gap-2 rounded-lg px-4 py-2"><Save className="h-4 w-4"/>{saving?'Saving…':'Save course'}</button>
  </form>
  <section className="mt-8"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5"/><h2 className="text-2xl font-semibold">Sections and units</h2></div>
   <form onSubmit={createSection} className="mt-4 flex gap-2"><input className="input flex-1" placeholder="New section title" value={sectionTitle} onChange={e=>setSectionTitle(e.target.value)}/><button className="btn-secondary inline-flex items-center gap-2 rounded-lg px-4"><Plus className="h-4 w-4"/>Add section</button></form>
   <div className="mt-5 space-y-5">{course.sections?.map((section:any)=><article key={section.id} className="card p-6"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">{section.title}</h3><button className="text-red-600" onClick={async()=>{if(confirm('Delete this section and all its units?')){await deleteSection({variables:{id:section.id}});await refetch();}}}><Trash2 className="h-4 w-4"/></button></div>
    <div className="mt-4 space-y-2">{section.lessons?.map((lesson:any)=><div key={lesson.id} className="flex items-center justify-between rounded-lg border p-3"><div><p className="font-medium">{lesson.title}</p><p className="text-xs text-gray-500">{lesson.durationMin} min{lesson.isFreePreview?' · Free preview':''}</p></div><div className="flex gap-3"><button className="text-sm text-primary-700" onClick={()=>setEditing({...lesson})}>Edit</button><button className="text-red-600" onClick={async()=>{await deleteLesson({variables:{id:lesson.id}});await refetch();}}><Trash2 className="h-4 w-4"/></button></div></div>)}</div>
    <div className="mt-4 grid gap-2 rounded-xl bg-gray-50 p-4 sm:grid-cols-2"><input className="input" placeholder="Unit title" value={lessonDraft[section.id]?.title??''} onChange={e=>setLessonDraft({...lessonDraft,[section.id]:{...lessonDraft[section.id],title:e.target.value}})}/><input type="number" min="0" className="input" placeholder="Length in minutes" value={lessonDraft[section.id]?.durationMin??''} onChange={e=>setLessonDraft({...lessonDraft,[section.id]:{...lessonDraft[section.id],durationMin:e.target.value}})}/><textarea className="input" placeholder="Unit description or written material" value={lessonDraft[section.id]?.description??''} onChange={e=>setLessonDraft({...lessonDraft,[section.id]:{...lessonDraft[section.id],description:e.target.value}})}/><input type="url" className="input" placeholder="Video or media URL" value={lessonDraft[section.id]?.videoUrl??''} onChange={e=>setLessonDraft({...lessonDraft,[section.id]:{...lessonDraft[section.id],videoUrl:e.target.value}})}/><label className="text-sm"><input type="checkbox" checked={Boolean(lessonDraft[section.id]?.isFreePreview)} onChange={e=>setLessonDraft({...lessonDraft,[section.id]:{...lessonDraft[section.id],isFreePreview:e.target.checked}})}/> Free preview</label><button className="btn-secondary rounded-lg px-4 py-2" onClick={()=>void createLesson(section.id)}>Add unit</button></div>
   </article>)}</div>
  </section>
  {editing&&<div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4"><section className="w-full max-w-lg space-y-3 rounded-2xl bg-white p-6"><h2 className="text-xl font-semibold">Edit unit</h2><input className="input w-full" value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/><textarea className="input w-full" value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/><input type="url" className="input w-full" placeholder="Video or media URL" value={editing.videoUrl??''} onChange={e=>setEditing({...editing,videoUrl:e.target.value})}/><input type="number" className="input w-full" value={editing.durationMin??0} onChange={e=>setEditing({...editing,durationMin:e.target.value})}/><label className="text-sm"><input type="checkbox" checked={Boolean(editing.isFreePreview)} onChange={e=>setEditing({...editing,isFreePreview:e.target.checked})}/> Free preview</label><div className="flex justify-end gap-3"><button className="btn-secondary rounded-lg px-4 py-2" onClick={()=>setEditing(null)}>Cancel</button><button className="btn-primary rounded-lg px-4 py-2" onClick={()=>void saveLesson()}>Save unit</button></div></section></div>}
  </>}</main></RoleGate>;
}
