apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mymusic-coach
configMapGenerator:
  - name: application-identity-schema
    files:
      - 001-identity.sql
      - 002-practice.sql
