apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../workloads/keycloak

patches:
  - target:
      group: k8s.keycloak.org
      version: v2beta1
      kind: Keycloak
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/hostname/hostname
        value: https://auth.mymusic.coach
