#!/bin/bash
# ── Moodle entrypoint ────────────────────────────────────────────
# Generates config.php from environment on every start (no stale state
# after container recreates). Runs the CLI installer only when the
# database is fresh (mdl_config table absent).
set -e

: "${MOODLE_DATABASE_TYPE:=pgsql}"
: "${MOODLE_DATABASE_HOST:=moodle-db}"
: "${MOODLE_DATABASE_PORT_NUMBER:=5432}"
: "${MOODLE_DATABASE_USER:=moodle}"
: "${MOODLE_DATABASE_PASSWORD:=moodle_dev_pw}"
: "${MOODLE_DATABASE_NAME:=moodle}"
: "${MOODLE_USERNAME:=admin}"
: "${MOODLE_PASSWORD:=moodle_admin_pw}"
: "${MOODLE_EMAIL:=admin@mymusic.coach}"
: "${MOODLE_SITE_NAME:=My Music Coach}"
: "${MOODLE_HOST:=learn.mymusic-coach.test}"
: "${MOODLE_SSLPROXY:=false}"
: "${MOODLE_DATA_DIR:=/var/moodledata}"
: "${MOODLE_WWWROOT:=http://${MOODLE_HOST}}"

CONFIG_FILE="/var/www/html/config.php"

# ── Wait for the database ──────────────────────────────────────
echo "[moodle] Waiting for database at ${MOODLE_DATABASE_HOST}:${MOODLE_DATABASE_PORT_NUMBER}..."
until bash -c "echo > /dev/tcp/${MOODLE_DATABASE_HOST}/${MOODLE_DATABASE_PORT_NUMBER}" 2>/dev/null; do
  echo "[moodle] Database not ready — retrying in 5s..."
  sleep 5
done
sleep 3

# ── Generate config.php from environment ──────────────────────
# Done on EVERY start so a container recreate never leaves a stale
# config pointing at the wrong host/wwwroot.
echo "[moodle] Writing config.php..."

cat > "$CONFIG_FILE" << EOPHP
<?php  // Moodle configuration — auto-generated by docker-entrypoint.sh
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = '${MOODLE_DATABASE_TYPE}';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${MOODLE_DATABASE_HOST}';
\$CFG->dbname    = '${MOODLE_DATABASE_NAME}';
\$CFG->dbuser    = '${MOODLE_DATABASE_USER}';
\$CFG->dbpass    = '${MOODLE_DATABASE_PASSWORD}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = array('dbport' => '${MOODLE_DATABASE_PORT_NUMBER}', 'dbsocket' => '');

\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${MOODLE_DATA_DIR}';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02777;
EOPHP

if [ "${MOODLE_SSLPROXY}" = "true" ]; then
  echo "\$CFG->sslproxy = true;" >> "$CONFIG_FILE"
fi

echo "require_once(__DIR__ . '/lib/setup.php');" >> "$CONFIG_FILE"
chown www-data:www-data "$CONFIG_FILE"
echo "[moodle] config.php written."

# ── Install only on a fresh database ──────────────────────────
# Check for mdl_config table; if absent the schema has never been created.
# Uses native pgsql extension (pdo_pgsql is not present in the moodlehq image).
# On any connection failure we assume installed — safe default that avoids
# running the CLI installer against an existing database.
DB_READY=$(php -r "
\$conn = @pg_connect('host=${MOODLE_DATABASE_HOST} port=${MOODLE_DATABASE_PORT_NUMBER} dbname=${MOODLE_DATABASE_NAME} user=${MOODLE_DATABASE_USER} password=${MOODLE_DATABASE_PASSWORD}');
if (!\$conn) { echo 'installed'; exit; }
\$r = pg_query(\$conn, \"SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='mdl_config'\");
echo (\$r && pg_fetch_result(\$r, 0, 0)) ? 'installed' : 'fresh';
")

if [ "$DB_READY" = "fresh" ]; then
  echo "[moodle] Fresh database — running CLI installer (this may take several minutes)..."
  php /var/www/html/admin/cli/install.php \
    --lang=en \
    --wwwroot="${MOODLE_WWWROOT}" \
    --dataroot="${MOODLE_DATA_DIR}" \
    --dbtype="${MOODLE_DATABASE_TYPE}" \
    --dbhost="${MOODLE_DATABASE_HOST}" \
    --dbport="${MOODLE_DATABASE_PORT_NUMBER}" \
    --dbname="${MOODLE_DATABASE_NAME}" \
    --dbuser="${MOODLE_DATABASE_USER}" \
    --dbpass="${MOODLE_DATABASE_PASSWORD}" \
    --prefix=mdl_ \
    --fullname="${MOODLE_SITE_NAME}" \
    --shortname="mymusic_coach" \
    --adminuser="${MOODLE_USERNAME}" \
    --adminpass="${MOODLE_PASSWORD}" \
    --adminemail="${MOODLE_EMAIL}" \
    --non-interactive \
    --agree-license
  echo "[moodle] Installation complete."
  # installer (re)creates config.php as root; restore ownership
  chown www-data:www-data "$CONFIG_FILE"
else
  echo "[moodle] Database already installed — skipping CLI installer."
fi

# ── Enable web services + inject API token ────────────────────
# Script is idempotent; safe to run on every start.
echo "[moodle] Configuring web services..."
php /usr/local/bin/moodle-setup-webservice.php

# ── Configure Keycloak OAuth2 / auto-login ────────────────────
# Script is idempotent; skipped if MOODLE_OIDC_CLIENT_ID is unset.
echo "[moodle] Configuring Keycloak OAuth2 SSO..."
php /usr/local/bin/moodle-setup-oauth2.php

# ── Configure Visual Homogeneity (Theme) ────────────────────
echo "[moodle] Injecting custom theme and dashboard link..."
php -r "
define('CLI_SCRIPT', true);
require('/var/www/html/config.php');
set_config('scss', 'body { background-color: #0f172a; color: #f8fafc; } .navbar { background-color: #1e293b !important; } .navbar a { color: #f8fafc !important; }', 'theme_boost');
\$dashboard_link = '<div style=\"background-color: #1e293b; padding: 10px; text-align: center;\"><a href=\"'.getenv('FRONTEND_URL').'/dashboard\" style=\"color: #3b82f6; font-weight: bold;\">&larr; Back to My Music Coach Dashboard</a></div>';
set_config('additionalhtmltopofbody', \$dashboard_link);
set_config('noemailever', 1); // Disable Moodle native emails to let the central platform handle them
"

exec "$@"
