apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../platform/cloudflare-tunnel

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
